name: todo_list_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase core + services
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.0

  # Web-specific compatibility (pulled automatically but good to pin manually)
  firebase_auth_web: ^5.8.13
  cloud_firestore_web: ^3.10.5
  js: ^0.6.7 

  # State management
  provider: ^6.1.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
